[package]
name = "tagpro-eu-analysis"
version = "0.1.0"
authors = ["Tumblewood"]
edition = "2024"

[dependencies]
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
num-derive = "^0.4"
num-traits = "^0.2"
base64 = "^0.21"